// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xmsg_head2.proto

#include "xmsg_head2.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace xmsg {
class XMsgHead_2DefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<XMsgHead_2> _instance;
} _XMsgHead_2_default_instance_;
}  // namespace xmsg
static void InitDefaultsscc_info_XMsgHead_2_xmsg_5fhead2_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::xmsg::_XMsgHead_2_default_instance_;
    new (ptr) ::xmsg::XMsgHead_2();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::xmsg::XMsgHead_2::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_XMsgHead_2_xmsg_5fhead2_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_XMsgHead_2_xmsg_5fhead2_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_xmsg_5fhead2_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_xmsg_5fhead2_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_xmsg_5fhead2_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_xmsg_5fhead2_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xmsg::XMsgHead_2, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::xmsg::XMsgHead_2, msg_size_),
  PROTOBUF_FIELD_OFFSET(::xmsg::XMsgHead_2, msg_str_),
  PROTOBUF_FIELD_OFFSET(::xmsg::XMsgHead_2, msg_type_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::xmsg::XMsgHead_2)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::xmsg::_XMsgHead_2_default_instance_),
};

const char descriptor_table_protodef_xmsg_5fhead2_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020xmsg_head2.proto\022\004xmsg\"A\n\nXMsgHead_2\022\020"
  "\n\010msg_size\030\001 \001(\005\022\017\n\007msg_str\030\002 \001(\t\022\020\n\010msg"
  "_type\030\003 \001(\005b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_xmsg_5fhead2_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_xmsg_5fhead2_2eproto_sccs[1] = {
  &scc_info_XMsgHead_2_xmsg_5fhead2_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_xmsg_5fhead2_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xmsg_5fhead2_2eproto = {
  false, false, descriptor_table_protodef_xmsg_5fhead2_2eproto, "xmsg_head2.proto", 99,
  &descriptor_table_xmsg_5fhead2_2eproto_once, descriptor_table_xmsg_5fhead2_2eproto_sccs, descriptor_table_xmsg_5fhead2_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_xmsg_5fhead2_2eproto::offsets,
  file_level_metadata_xmsg_5fhead2_2eproto, 1, file_level_enum_descriptors_xmsg_5fhead2_2eproto, file_level_service_descriptors_xmsg_5fhead2_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_xmsg_5fhead2_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_xmsg_5fhead2_2eproto)), true);
namespace xmsg {

// ===================================================================

void XMsgHead_2::InitAsDefaultInstance() {
}
class XMsgHead_2::_Internal {
 public:
};

XMsgHead_2::XMsgHead_2(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:xmsg.XMsgHead_2)
}
XMsgHead_2::XMsgHead_2(const XMsgHead_2& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  msg_str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_msg_str().empty()) {
    msg_str_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_msg_str(),
      GetArena());
  }
  ::memcpy(&msg_size_, &from.msg_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&msg_type_) -
    reinterpret_cast<char*>(&msg_size_)) + sizeof(msg_type_));
  // @@protoc_insertion_point(copy_constructor:xmsg.XMsgHead_2)
}

void XMsgHead_2::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_XMsgHead_2_xmsg_5fhead2_2eproto.base);
  msg_str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&msg_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&msg_type_) -
      reinterpret_cast<char*>(&msg_size_)) + sizeof(msg_type_));
}

XMsgHead_2::~XMsgHead_2() {
  // @@protoc_insertion_point(destructor:xmsg.XMsgHead_2)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void XMsgHead_2::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  msg_str_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void XMsgHead_2::ArenaDtor(void* object) {
  XMsgHead_2* _this = reinterpret_cast< XMsgHead_2* >(object);
  (void)_this;
}
void XMsgHead_2::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void XMsgHead_2::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const XMsgHead_2& XMsgHead_2::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_XMsgHead_2_xmsg_5fhead2_2eproto.base);
  return *internal_default_instance();
}


void XMsgHead_2::Clear() {
// @@protoc_insertion_point(message_clear_start:xmsg.XMsgHead_2)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_str_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&msg_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&msg_type_) -
      reinterpret_cast<char*>(&msg_size_)) + sizeof(msg_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XMsgHead_2::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 msg_size = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          msg_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string msg_str = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_msg_str();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "xmsg.XMsgHead_2.msg_str"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 msg_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          msg_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* XMsgHead_2::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xmsg.XMsgHead_2)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 msg_size = 1;
  if (this->msg_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_msg_size(), target);
  }

  // string msg_str = 2;
  if (this->msg_str().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_msg_str().data(), static_cast<int>(this->_internal_msg_str().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "xmsg.XMsgHead_2.msg_str");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_msg_str(), target);
  }

  // int32 msg_type = 3;
  if (this->msg_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_msg_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xmsg.XMsgHead_2)
  return target;
}

size_t XMsgHead_2::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xmsg.XMsgHead_2)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msg_str = 2;
  if (this->msg_str().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_msg_str());
  }

  // int32 msg_size = 1;
  if (this->msg_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_msg_size());
  }

  // int32 msg_type = 3;
  if (this->msg_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_msg_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void XMsgHead_2::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:xmsg.XMsgHead_2)
  GOOGLE_DCHECK_NE(&from, this);
  const XMsgHead_2* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<XMsgHead_2>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:xmsg.XMsgHead_2)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:xmsg.XMsgHead_2)
    MergeFrom(*source);
  }
}

void XMsgHead_2::MergeFrom(const XMsgHead_2& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:xmsg.XMsgHead_2)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.msg_str().size() > 0) {
    _internal_set_msg_str(from._internal_msg_str());
  }
  if (from.msg_size() != 0) {
    _internal_set_msg_size(from._internal_msg_size());
  }
  if (from.msg_type() != 0) {
    _internal_set_msg_type(from._internal_msg_type());
  }
}

void XMsgHead_2::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:xmsg.XMsgHead_2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void XMsgHead_2::CopyFrom(const XMsgHead_2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xmsg.XMsgHead_2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XMsgHead_2::IsInitialized() const {
  return true;
}

void XMsgHead_2::InternalSwap(XMsgHead_2* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  msg_str_.Swap(&other->msg_str_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XMsgHead_2, msg_type_)
      + sizeof(XMsgHead_2::msg_type_)
      - PROTOBUF_FIELD_OFFSET(XMsgHead_2, msg_size_)>(
          reinterpret_cast<char*>(&msg_size_),
          reinterpret_cast<char*>(&other->msg_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata XMsgHead_2::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace xmsg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::xmsg::XMsgHead_2* Arena::CreateMaybeMessage< ::xmsg::XMsgHead_2 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xmsg::XMsgHead_2 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
